variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:18.09-dind

buildanddeploy:
  stage: build
  image: docker:18.09

  script:
    - echo "Starting the script"
    - echo "Installing required tools"
    - apk add git curl
    - echo "Git and Curl Installed"
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - echo "Kubectl Installed"
    - echo "Running Build and Deploy Script"
    - sh ./build_and_deploy.sh
  only:
    - master
  when: on_success