variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2

image: "harbor-repo.vmware.com/dockerhub-proxy-cache/library/python:3.7.1-slim"

services:
  - docker:18.09-dind
stages:
  - code_analysis
  - build
pylint_job:
  stage: code_analysis
#  image: python:3.7-slim
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
    - pip install -r ci_requirements.txt
  script:
    - pylint --fail-under 10 --output-format=text $(find . -path ./.tox -prune -false -o -type f -name "*.py") | tee /tmp/pylint.txt  || echo -e "\n masking pylint's non-zero exit code \n"
    - sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' /tmp/pylint.txt > public/badges/$CI_JOB_NAME.score
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo -e "\n\n#### Your score is: $(cat public/badges/$CI_JOB_NAME.score) ####\n\n"
  artifacts:
    paths:
      - public
  only:
    - master
  when: always

mypy_job:
  stage: code_analysis
#  image: python:3.7-slim
  before_script:
    - pip install -r ci_requirements.txt
  script:
    - mypy --disable-error-code name-defined --disable-error-code attr-defined --show-error-codes --show-error-context --strict --check-untyped-defs --pretty $(find . -path ./.tox -prune -false -o -type f -name "*.py") | tee /tmp/mypy.txt || echo -n "mypy returned failure"
  only:
    - master
  when: always

build_job:
  stage: build
  image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/docker:18.09
  script:
    - echo "Starting the script"
    - echo "Installing required tools"
    - apk add git curl
    - echo "Git and Curl Installed"
    - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
    - chmod +x kubectl
    - mv ./kubectl /usr/local/bin/kubectl
    - echo "Kubectl Installed"
    - echo "Running Build and Deploy Script"
    - sh ./buildAndDeploy.sh
  only:
    - master
  when: on_success

pages:
  stage: build
  image: harbor-repo.vmware.com/dockerhub-proxy-cache/library/alpine:latest
  script:
    - echo
  artifacts:
    paths:
      - public
  only:
    - master
