# Global options:
[mypy]
disable_error_code=name-defined,attr-defined
show_error_codes = True
show_error_context = True
check_untyped_defs = True
strict_optional = False
pretty = True

#warn_return_any = True
#warn_unused_configs = True
