[pytest]
;markers =
;    test1: mark a test as a test1.
;    test2: mark a test as a test2.
;    test3: mark a test as a test3.

testpaths = tests
log_cli_level = INFO
log_file_level = INFO
addopts = -ra --capture=no --verbose --verbose
;--html=logs/mangle-yaan-execution-report.html --self-contained-html