apiVersion: batch/v1
kind: Job
metadata:
  name: mangle-yaan-job
spec:
  template:
    spec:
      containers:
      - name: mangle-yaan-job
        image: vmware-docker-csp-tools.bintray.io/mangle-yaan:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: run_id
            value: "abcd"
          - name: MYCONFIG
            value: "/mangle-yaan/config/my.json"
          - name: TESTRUNNER_PARAMS
            value: "/mangle-yaan/tests/test_dummy.py"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      restartPolicy: "Never"
      imagePullSecrets:
      - name: mangle-yaan-secret
  backoffLimit: 3