apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resiliency-all-workloads-csp-apis-decc
spec:
  schedule: "0 18 * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resiliency-all-workloads-csp-apis-decc
            image: vmwaresaas.jfrog.io/csp/resiliency-workload:latest
            imagePullPolicy: Always
            env:
              - name: WORKLOAD_ID
                value: "hk2VNSAL84rpJ5zRYDi3ji"
              - name: VERSION
                value: "0"
              - name: TAG
                value: "RunByCronJob"
              - name: TEST_SUITE_NAME
                value: "test_csp_apis_when_gaz_not_reachable,test_sscp_apis_when_gaz_not_reachable,test_am_api_when_a_service_down,test_commerce_api_when_a_service_down,test_slc_api_when_a_service_down,test_onboarding_api_when_a_service_down"
            resources:
              limits:
                memory: "2Gi"
                cpu: "1000m"
          restartPolicy: "Never"
          imagePullSecrets:
          - name: auto-secret
      backoffLimit: 1