apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selenium-hub-ingress
  namespace: ara-mangle-yaan
  labels:
    app: selenium-hub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: avi-lb
  defaultBackend:
    service:
      name: selenium-hub-svc
      port:
        number: 4444
  rules:
    - host: selenium-mangle-yaan.ara.decc.company.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: selenium-hub-svc
                port:
                  number: 4444
        # - path:
        #   backend:
        #     serviceName: e2e-qe-mysql
        #     servicePort: 30002