apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-node-chrome
  namespace: ara-mangle-yaan
  labels:
    app: selenium-node-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-node-chrome
  template:
    metadata:
      labels:
        app: selenium-node-chrome
    spec:
      containers:
        - name: selenium-node-chrome
          image: harbor-repo.company.com/csp_qe/selenium/node-chrome-debug:3.141
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5900
          resources:
            requests:
              memory: "2048M"
              cpu: "1000m"
            limits:
              memory: "2048M"
              cpu: "1000m"
          env:
            - name: HUB_HOST
              value: "selenium-hub-svc"
            - name: HUB_PORT
              value: "4444"
            - name: HUB_PORT_4444_TCP_ADDR
              value: "selenium-hub-svc"
            - name: HUB_PORT_4444_TCP_PORT
              value: "4444"
            - name: NODE_MAX_INSTANCES
              value: "5"
            - name: NODE_MAX_SESSION
              value: "5"
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory