apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameday-deployment
  labels:
    app: gameday-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  gameday-service
  template:
    metadata:
      labels:
        app:  gameday-service
    spec:
      containers:
      - name:  gameday-service
        image: harbor-repo.vmware.com/csp_qe/gameday-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        resources:
          requests:
            memory: "1Gi"
            cpu: "800m"
          limits:
            memory: "1Gi"
            cpu: "800m"
---
apiVersion: v1
kind: Service
metadata:
  name: gameday-svc
spec:
  selector:
    app: gameday-service
  ports:
  - port: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gameday-service-ingress
  labels:
    app: gameday-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gameday-service.svc-stage.eng.vmware.com
    http:
      paths:
      - backend:
          serviceName: gameday-svc
          servicePort: 5000

