apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJ1Z0F3SUJBZ0lNRldiL0J6REFtS0R1WkpoUE1BMEdDU3FHU0liM0RRRUJDd1VBTUJVeEV6QVIKQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13SGhjTk1UZ3hNVEV5TVRJMU9EUTRXaGNOTWpneE1URXhNVEkxT0RRNApXakFWTVJNd0VRWURWUVFERXdwcmRXSmxjbTVsZEdWek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTBZZzIrNXJaOTF4ZkdUQmJzYktuRlJiZ3VSeGY5VU5VTGYvaU1ob2ZDb2N1S1ZzTTFCYnIKS0NuRjBUajdPSnVwamMxNmNzOTBGc3JRQW16ekFXTHRLVFZYV092VTNOdUVNT0p5Z3ZjWVJMbzdqUmRSWGJGSQpLMGsxZUZROU83RDdodzVXdWJCT0dCYUFMaU5NUkM5dWliNzUyY0IvQTdBTWVIOG9xNG9pMWsyb3NOUTFTMkU1Cmtqd2haUkZUQkJlK2wwYmY3WjIzKytwRnhKbjV0K1FyR0lZQUh5SEZZRnE2NDllTHAxNmdPZWdKYzVZak8vcDkKRnpzczIwQVpEK3RqbjgzYzF0RnRCSThTRVUwblpPbmQ1ckdMK2I3Y1dtUWVkY0t2RGRXRkZFUUxwOTFxWU5YZAovbzVibGdzTW90Qm43UzAwd3A3c3QzWWZKWkVwN3QxNDRRSURBUUFCb3lNd0lUQU9CZ05WSFE4QkFmOEVCQU1DCkFRWXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXVlBkL2J6WnFGbzEKQXBLMzJOdEVvNVNiY0hjNTNGSDhvaXRnb0NqNTljOVJMTmRXNmIyQVRPek9aNjJYTENraFdyaFJLWG1iRUwzcwpOcXdCNnNBQWM3U0JHQXRVRXRCeldJZjBFZEc1NllSckRwRWYzM1YxL2FkZVRyT1E5ZFJTTEEwNjR5ejNNK1dtClUvUk5nYVEraEs5V1Z3eWJuWkRoSjlwdTZiUXJ4cW5zTzRJM1pJcGF6clVLNXl6V011clpibG8zd0dHUW5PL2wKeWV4MkhWOEZPNDFnSks5MEM5eDYwVlI2WGptWWI5SUdHSUI1cTh6WWxjUmZSTCtPSEZ0OFdhRFE5ajhwM3lyLworZnkrYUVDTmNjcVl0Sm40MHZ5UkRTQThlMHRYSEhoK2R3ZG5CV0NndnBORlI0eDJsWFdIc0Vya3lnZ0Q1WlN1CmlYVExlRFp3RFE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api-k8s-csp01-dev-us-west-n5d70g-790387334.us-west-2.elb.amazonaws.com
  name: /vdp/orgs/csp/clusters/csp01-dev-us-west-2
contexts:
- context:
    cluster: /vdp/orgs/csp/clusters/csp01-dev-us-west-2
    namespace: csp-app-dev
    user: mtarun@vmware.com:/vdp/orgs/csp/clusters/csp01-dev-us-west-2
  name: mtarun@vmware.com:/vdp/orgs/csp/clusters/csp01-dev-us-west-2
current-context: mtarun@vmware.com:/vdp/orgs/csp/clusters/csp01-dev-us-west-2
kind: Config
preferences: {}
users:
- name: mtarun@vmware.com:/vdp/orgs/csp/clusters/csp01-dev-us-west-2
  user:
    token: 78tL1dZMzcntKjLm5HZCWaGbFV0DQWRh03Jfcz4qYZ34aNwKYnUvtNstaBMM251L
