apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: am-deny-external-egress
spec:
  podSelector:
    matchLabels:
      app: csp-account-management-mvc
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector:
        matchLabels:
          name: csp-app-preview